/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xymeznfxzytyzmfimbdp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5bWV6bmZ4enl0eXptZmltYmRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI5MDUxMjgsImV4cCI6MjA5ODQ4MTEyOH0.-B7_lMCl13mR5emoqB5USM4BOgiYadF5lZ-709iFdw4"